### ISSUE TITLE
main.py does not run 'as is' on penn data

### ISSUE THREAD

**Issue by francoishernandez** [Stonesjtu/Pytorch-NCE#1]
Hi there,

I'm trying out your code and couldn't run it 'as is' on penn data. I changed the import of `data_sms` to `data` in `main.py`.
Maybe you left this from some tryouts on another dataset?

Thanks for your implementation anyways.
F

**Comment by Stonesjtu** [comment]
This repo is under active developing recently, I have merged the latest branch into master.  Following the first part of `README.txt` could produce a working but not perfect NCE LM.
Feel free to open issues.
Hope it will help you.
